/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as NearbyRouteImport } from './routes/nearby'
import { Route as NewsjajanRouteImport } from './routes/newsjajan'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBugRouteImport } from './routes/_authenticated/bug'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedNewRouteImport } from './routes/_authenticated/new'
import { Route as AuthenticatedNotifRouteImport } from './routes/_authenticated/notif'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedWishlistRouteImport } from './routes/_authenticated/wishlist'
import { Route as DetailIdRouteImport } from './routes/detail.$id'
import { Route as AuthenticatedChatUserIdRouteImport } from './routes/_authenticated/chat.$userId'
import { Route as AuthenticatedEditIdRouteImport } from './routes/_authenticated/edit.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyRoute = NearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsjajanRoute = NewsjajanRouteImport.update({
  id: '/newsjajan',
  path: '/newsjajan',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBugRoute = AuthenticatedBugRouteImport.update({
  id: '/bug',
  path: '/bug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewRoute = AuthenticatedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotifRoute = AuthenticatedNotifRouteImport.update({
  id: '/notif',
  path: '/notif',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWishlistRoute = AuthenticatedWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DetailIdRoute = DetailIdRouteImport.update({
  id: '/detail/$id',
  path: '/detail/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatUserIdRoute = AuthenticatedChatUserIdRouteImport.update({
  id: '/chat/$userId',
  path: '/chat/$userId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEditIdRoute = AuthenticatedEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/nearby': typeof NearbyRoute
  '/newsjajan': typeof NewsjajanRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bug': typeof AuthenticatedBugRoute
  '/help': typeof AuthenticatedHelpRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/new': typeof AuthenticatedNewRoute
  '/notif': typeof AuthenticatedNotifRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/detail/$id': typeof DetailIdRoute
  '/chat/$userId': typeof AuthenticatedChatUserIdRoute
  '/edit/$id': typeof AuthenticatedEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/nearby': typeof NearbyRoute
  '/newsjajan': typeof NewsjajanRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bug': typeof AuthenticatedBugRoute
  '/help': typeof AuthenticatedHelpRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/new': typeof AuthenticatedNewRoute
  '/notif': typeof AuthenticatedNotifRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/detail/$id': typeof DetailIdRoute
  '/chat/$userId': typeof AuthenticatedChatUserIdRoute
  '/edit/$id': typeof AuthenticatedEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/nearby': typeof NearbyRoute
  '/newsjajan': typeof NewsjajanRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/bug': typeof AuthenticatedBugRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/new': typeof AuthenticatedNewRoute
  '/_authenticated/notif': typeof AuthenticatedNotifRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/wishlist': typeof AuthenticatedWishlistRoute
  '/detail/$id': typeof DetailIdRoute
  '/_authenticated/chat/$userId': typeof AuthenticatedChatUserIdRoute
  '/_authenticated/edit/$id': typeof AuthenticatedEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/nearby'
    | '/newsjajan'
    | '/onboarding'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/admin'
    | '/bug'
    | '/help'
    | '/messages'
    | '/new'
    | '/notif'
    | '/profile'
    | '/settings'
    | '/wishlist'
    | '/detail/$id'
    | '/chat/$userId'
    | '/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/nearby'
    | '/newsjajan'
    | '/onboarding'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/admin'
    | '/bug'
    | '/help'
    | '/messages'
    | '/new'
    | '/notif'
    | '/profile'
    | '/settings'
    | '/wishlist'
    | '/detail/$id'
    | '/chat/$userId'
    | '/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/nearby'
    | '/newsjajan'
    | '/onboarding'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/bug'
    | '/_authenticated/help'
    | '/_authenticated/messages'
    | '/_authenticated/new'
    | '/_authenticated/notif'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/wishlist'
    | '/detail/$id'
    | '/_authenticated/chat/$userId'
    | '/_authenticated/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  NearbyRoute: typeof NearbyRoute
  NewsjajanRoute: typeof NewsjajanRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  DetailIdRoute: typeof DetailIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby': {
      id: '/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof NearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsjajan': {
      id: '/newsjajan'
      path: '/newsjajan'
      fullPath: '/newsjajan'
      preLoaderRoute: typeof NewsjajanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bug': {
      id: '/_authenticated/bug'
      path: '/bug'
      fullPath: '/bug'
      preLoaderRoute: typeof AuthenticatedBugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new': {
      id: '/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthenticatedNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notif': {
      id: '/_authenticated/notif'
      path: '/notif'
      fullPath: '/notif'
      preLoaderRoute: typeof AuthenticatedNotifRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wishlist': {
      id: '/_authenticated/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof AuthenticatedWishlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/detail/$id': {
      id: '/detail/$id'
      path: '/detail/$id'
      fullPath: '/detail/$id'
      preLoaderRoute: typeof DetailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat/$userId': {
      id: '/_authenticated/chat/$userId'
      path: '/chat/$userId'
      fullPath: '/chat/$userId'
      preLoaderRoute: typeof AuthenticatedChatUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/edit/$id': {
      id: '/_authenticated/edit/$id'
      path: '/edit/$id'
      fullPath: '/edit/$id'
      preLoaderRoute: typeof AuthenticatedEditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBugRoute: typeof AuthenticatedBugRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNewRoute: typeof AuthenticatedNewRoute
  AuthenticatedNotifRoute: typeof AuthenticatedNotifRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWishlistRoute: typeof AuthenticatedWishlistRoute
  AuthenticatedChatUserIdRoute: typeof AuthenticatedChatUserIdRoute
  AuthenticatedEditIdRoute: typeof AuthenticatedEditIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBugRoute: AuthenticatedBugRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNewRoute: AuthenticatedNewRoute,
  AuthenticatedNotifRoute: AuthenticatedNotifRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWishlistRoute: AuthenticatedWishlistRoute,
  AuthenticatedChatUserIdRoute: AuthenticatedChatUserIdRoute,
  AuthenticatedEditIdRoute: AuthenticatedEditIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  NearbyRoute: NearbyRoute,
  NewsjajanRoute: NewsjajanRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  DetailIdRoute: DetailIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
